/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Velmo
 * Backend API for Velmo
 * OpenAPI spec version: 1.0
 */
import type { CreateUserRequest, Model } from '.././model'

import { customAxios } from '.././axiosInstance'

export const getUser = () => {
    const userCreate = (createUserRequest: CreateUserRequest) => {
        return customAxios<Model>({
            url: `/user/create`,
            method: 'POST',
            headers: { 'Content-Type': 'application/json' },
            data: createUserRequest,
        })
    }
    const userExists = () => {
        return customAxios<Model>({ url: `/user/exists`, method: 'GET' })
    }
    return { userCreate, userExists }
}
export type UserCreateResult = NonNullable<
    Awaited<ReturnType<ReturnType<typeof getUser>['userCreate']>>
>
export type UserExistsResult = NonNullable<
    Awaited<ReturnType<ReturnType<typeof getUser>['userExists']>>
>
